### PR TITLE
Codecompass webserver handles the workspace directory in inconsistent…

### LINKED ISSUE #378: Codecompass webserver handles the workspace directory in inconsistent way
On starting CodeCompass webserver is supposed to iterate over the sub directories in the specified "workspace" directory, and tries to open the project_info.json in the sub directory. If project_info.json is not found than that sub directory (and that project) is supposed to skip.
However, currently the webserver handles regular files in the similar way (naturally, there will be no project_info.json under). Moreover, if any of the attempts fail, we do not continue to the next sub directory but throw exception and leave the loop.

### PR DESCRIPTION
**Pull request by zporky**
… way.

Two modifications:
 (1) skip regular files.
 (2) when no project_info found continue instead of throw.
Fix #378.

### CODE REVIEW

File: webserver/include/webserver/pluginhelper.h [hunk 1]
```diff
@@ -59,7 +62,7 @@ inline void registerPluginSimple(
         << "Skip project '" << project << "', because no database "
         << "connection string can be found for it in the '"
         << projectInfo << "' file!";
-      throw std::runtime_error("No db connection string!");
+      continue;
```
Comment (csordasmarton) [inline webserver/include/webserver/pluginhelper.h]: There is also one place below in this for loop where we can throw an exception:
https://github.com/Ericsson/CodeCompass/blob/e5e3acda7a8be21947fb583ac99a9f3ae73823d9/webserver/include/webserver/pluginhelper.h#L74
