### PR TITLE
Left side and file content menu fix

### LINKED ISSUE #219: Right menu click on non parsed files
Right clicking a non parsed file doesn't show the correct menu: 

cc_right_menu

It throws the following error message in the web console:
```console
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object._markUsages (Text.js?1509964427868:433)
    at Object._eventHandler (Text.js?1509964427868:408)
    at Text.js?1509964427868:256
    at signal (codemirror.js:1156)
    at signalDOMEvent (codemirror.js:1165)
    at CodeMirror$1.onMouseDown (codemirror.js:7224)
    at HTMLDivElement.<anonymous> (codemirror.js:3872)
_markUsages @ Text.js?1509964427868:433
_eventHandler @ Text.js?1509964427868:408
(anonymous) @ Text.js?1509964427868:256
signal @ codemirror.js:1156
signalDOMEvent @ codemirror.js:1165
onMouseDown @ codemirror.js:7224
(anonymous) @ codemirror.js:3872
```

### PR DESCRIPTION
**Pull request by intjftw**
Fixed the File Manager menu to not show C++ options if the file is not parsed. 
Fixed the file content menu to not show menu options that depend on AST node info. 
Closes #219

### CODE REVIEW

File: plugins/cpp/service/src/cppservice.cpp [hunk 1]
```diff
@@ -1238,7 +1238,7 @@ void CppServiceHandler::getFileDiagramTypes(
     return_["This module depends on"]               = EXTERNAL_DEPENDENCY;
     return_["Users of this module"]                 = EXTERNAL_USERS;
   }
-  else
+  else if (file->parseStatus != model::File::PSNone)
```
Comment (bruntib) [inline plugins/cpp/service/src/cppservice.cpp:1241]:
```suggestion
  else if (file->type == "CPP")
```
This way we could also filter those files which are parsed by another plugin.
